import os
import argparse
import re
from importlib.resources import files
from pathlib import Path

import pytorch_lightning as pl
import torch
from pytorch_lightning import Trainer

from hetairos.aggregator_train_val.utils import (
    read_yaml,
    set_seed,
    load_loggers,
    load_callbacks,
)
from hetairos.aggregator_train_val.model_module import ModelModule
from hetairos.aggregator_train_val.data_module import DataModule


def default_config_path():
    return str(files("hetairos.aggregator_train_val").joinpath("config.yaml"))


def normalize_devices(devices):
    if isinstance(devices, str) and devices.isdigit():
        return int(devices)
    return devices


def resolve_trainer_hardware(general_cfg):
    accelerator = general_cfg.get('accelerator', 'auto')
    devices = normalize_devices(general_cfg.get('devices', 'auto'))
    precision = general_cfg.get('precision', '32-true')

    if accelerator == 'auto':
        resolved_accelerator = 'gpu' if torch.cuda.is_available() else 'cpu'
    else:
        resolved_accelerator = accelerator

    if resolved_accelerator == 'cpu' and precision in ('16-mixed', '16', 16):
        precision = '32-true'

    return resolved_accelerator, devices, precision


def find_best_checkpoint(log_path):
    ckpt_files = list(log_path.glob('*.ckpt'))
    if not ckpt_files:
        raise FileNotFoundError(f"No checkpoints found in {log_path}")

    scored_ckpts = []
    for ckpt_path in ckpt_files:
        if ckpt_path.name == 'last.ckpt':
            continue
        match = re.search(r'multi_acc=([0-9]*\.?[0-9]+)', ckpt_path.stem)
        if not match:
            match = re.search(r'-([0-9]*\.?[0-9]+)$', ckpt_path.stem)
        if match:
            scored_ckpts.append((float(match.group(1)), ckpt_path))

    if scored_ckpts:
        return max(scored_ckpts, key=lambda item: item[0])[1]

    last_ckpt = log_path / 'last.ckpt'
    if last_ckpt.exists():
        return last_ckpt

    return max(ckpt_files, key=lambda p: p.stat().st_mtime)


# Parse command-line arguments to set parameters for the script
def parse_arguments():
    parser = argparse.ArgumentParser(description='Parameters for CNS tumor classification')
    parser.add_argument('--dataset', type=str,
                        required=True, help='Path to the dataset directory containing embeddings generated by a feature extractor, saved in .pt format')
    parser.add_argument('--label', type=str,
                        required=True,
                        help='Path to the slide label CSV file, which should contain columns including slide, family, probability vector, age, and location')
    parser.add_argument('--split', type=str, required=True,
                        help='Path to the dataset split file (YAML) containing train and test slide IDs, structured as {"train": [slide_id], "test": [slide_id]}')
    parser.add_argument('--mode', type=str, default='train', help='Operation mode: train or test')
    parser.add_argument('--data_aug', action='store_true', help='Apply data augmentation during training')
    parser.add_argument('--soft_labels', action='store_true', help='Use soft labels during training')
    parser.add_argument('--exp_name', type=str, default='default_exp', help='Identifier for the experiment')

    parser.add_argument('--output_dir', type=str, default='./predictions', help='Directory to save predictions')

    parser.add_argument('--model', type=str, default='ATransMIL', help='Model architecture to use')
    parser.add_argument('--groups', type=int, default=3, help='Number of slide matrix divisions')
    parser.add_argument('--classes', type=int, default=186, help='Output class number by the classifier')
    parser.add_argument('--cl_weight', type=float, default=20, help='Weight for contrastive loss')
    parser.add_argument('--config', type=str, default=default_config_path(), help='Path to configuration file')
    parser.add_argument('--label_map', type=str, required=True, help='Path to label mapping file')
    parser.add_argument('--accelerator', type=str, default=None, choices=['auto', 'cpu', 'gpu'],
                        help='Trainer accelerator. Use "auto" to select gpu when CUDA is available, otherwise cpu.')
    parser.add_argument('--devices', type=str, default=None,
                        help='Trainer devices setting, for example "auto", "1", or "0,1".')
    parser.add_argument('--precision', type=str, default=None,
                        help='Trainer precision, for example "32-true" or "16-mixed". CPU falls back to 32-true when precision is 16-mixed.')
    parser.add_argument('--resume', action='store_true', help='Resume training from the latest checkpoint')
    return parser.parse_args()


# Main function that orchestrates the training/testing process
def model_run(cfg):
    # Bug fix C: set seed unconditionally (was previously only set in non-train mode)
    set_seed(cfg['General']['seed'])

    # Load loggers and callbacks based on configuration
    loggers = load_loggers(cfg)
    callbacks = load_callbacks(cfg)

    # Initialize data and model module using the configuration
    data_module = DataModule(**cfg['Data'])
    model = ModelModule(**cfg)
    accelerator, devices, precision = resolve_trainer_hardware(cfg['General'])

    # Set up the PyTorch Lightning trainer with specified settings
    trainer = Trainer(
        logger=loggers,
        callbacks=callbacks,
        max_epochs=cfg['General']['epochs'],
        accelerator=accelerator,
        devices=devices,
        precision=precision,
        accumulate_grad_batches=cfg['General']['grad_acc'],
        check_val_every_n_epoch=1,
        num_sanity_val_steps=0
    )

    # Train or test based on the mode specified in the configuration
    if cfg['General']['mode'] == 'train':
        # Resume training if the resume flag is set
        if cfg['resume']:
            last_checkpoint_path = Path(cfg['General']['log_path']) / cfg['Model']['exp_name'] / 'last.ckpt'
            if not last_checkpoint_path.exists():
                raise FileNotFoundError(f"No resume checkpoint found at {last_checkpoint_path}")
            model = model.load_from_checkpoint(checkpoint_path=last_checkpoint_path, cfg=cfg)
        trainer.fit(model=model, datamodule=data_module)

    else:
        log_path = Path(cfg['General']['log_path']) / cfg['Model']['exp_name']
        best_checkpoint_path = find_best_checkpoint(log_path)
        print(f'Testing with checkpoint: {best_checkpoint_path}')
        loaded_model = model.load_from_checkpoint(checkpoint_path=best_checkpoint_path, Data=cfg['Data'])
        trainer.test(model=loaded_model, datamodule=data_module)


def main():
    # Parse command line arguments
    args = parse_arguments()

    # Read configuration from YAML file
    cfg = read_yaml(args.config)

    # Update configuration with command line arguments
    cfg['Data']['data_dir'] = args.dataset
    cfg['Data']['data_split'] = args.split
    cfg['Data']['label_file'] = args.label
    cfg['Data']['aug'] = args.data_aug
    cfg['Data']['soft_labels'] = args.soft_labels
    cfg['General']['mode'] = args.mode
    if args.accelerator is not None:
        cfg['General']['accelerator'] = args.accelerator
    if args.devices is not None:
        cfg['General']['devices'] = args.devices
    if args.precision is not None:
        cfg['General']['precision'] = args.precision
    cfg['Model']['exp_name'] = args.exp_name
    cfg['Model']['name'] = args.model
    cfg['Model']['group_num'] = args.groups
    cfg['Model']['n_classes'] = args.classes
    cfg['Model']['cl_w'] = args.cl_weight
    cfg['Data']['preds_save'] = args.output_dir
    cfg['Data']['label_mapping'] = args.label_map
    cfg['resume'] = args.resume

    # Run the main function
    model_run(cfg)


if __name__ == '__main__':
    main()
