General:
    fp16: True
    precision: 16-mixed
    multi_gpu_mode: dp
    gpus: [0]
    epochs: 100 
    grad_acc: 2
    frozen_bn: False
    patience: 10
    mode: test
    log_path: logs/

Data:
    data_dir: /omics/odcf/analysis/OE0606_projects/pancancer_histopathology/analysis/shared_playground/CNS_classification/embeddings/ProvGigaPath_256_1536_UKHD_FULL_dataset/pt_files
    data_split: ./split/Final_split_UKHD_mixed_mconf_fold1.yaml
    label_file: ./labels/labels_all_v12_108_UKHD_train_filled.csv
    aug: True
    soft_labels: False
    preds_save: ./results/
    label_mapping: ./felix_108_classes.yaml
    fold: 0
    batch_size: 1 
    age_loc_drop_prob: 0.7
    aug_prob: 0.5
    cls_count: 186
    loc_dict: {'Extracranial': 0, 'Infratentorial': 1, 'Intra- or Peri-Venticular': 2, 'Intra- or Supra-Sellar': 3, 'Pineal': 4, 'Spinal': 5, 'Supratentorial': 6}
    dim_age_embed: 32

Model:
    exp_name: Default
    name: TransMIL
    n_classes: 186
    embedding_size: 2560
    group_num: 3
    aug: False
    soft_labels: False
    dim_age_embed: 32
    
Optimizer:
    opt: lookahead_radam
    lr: 0.00001
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Loss:
    base_loss: CrossEntropyLoss
    loss_acronym: CE

